

# version: "3.8"

# services:
#   # Main Application
#   app:
#     build: .
#     container_name: cebleu
#     ports:
#       - "5000:5000"
#     environment:
#       NODE_ENV: production
#       # 🔹 Use your external Postgres instance
#       DATABASE_URL: postgresql://appuser:Str0ng%40P4ssw0rd%21@46.202.134.130:25432/ecomm1?sslmode=disable
#       SESSION_SECRET: pakistanzindabadhamfklassak
#       SMTP_HOST: mail.devnaza.com
#       SMTP_PORT: 587
#       SMTP_USER: test@devnaza.com
#       SMTP_PASS: "@AsDftest1"
#     volumes:
#       - ./uploads:/app/uploads
#     restart: unless-stopped

####################################################

# version: "3.8"

# services:
#   cebleu:
#     container_name: cebleu
#     build:
#       context: .
#       dockerfile: Dockerfile
#       args:
#         VITE_API_BASE_URL: ${VITE_API_BASE_URL}
#         VITE_SOCKET_URL: ${VITE_SOCKET_URL}
#         VITE_APP_NAME: ${VITE_APP_NAME}
#         VITE_DEFAULT_LANGUAGE: ${VITE_DEFAULT_LANGUAGE}
#         VITE_SUPPORTED_LANGUAGES: ${VITE_SUPPORTED_LANGUAGES}
#     env_file:
#       - .env
#     ports:
#       - "127.0.0.1:5103:5000"
#     volumes:
#       - ./uploads:/app/uploads
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD-SHELL", "wget -qO- http://localhost:5000/health || curl -fsS http://localhost:5000 || exit 1"]
#       interval: 30s
#       timeout: 5s
#       retries: 5

#######################################################

# version: "3.8"

# services:
#   # ------------------------------
#   # 🗄️ PostgreSQL Database
#   # ------------------------------
#   db:
#     image: postgres:16
#     container_name: postgres_db
#     restart: unless-stopped
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: cebleu_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

#   # ------------------------------
#   # 🚀 Your App / Backend
#   # ------------------------------
#   cebleu:
#     container_name: cebleu
#     build:
#       context: .
#       dockerfile: Dockerfile
#       args:
#         VITE_API_BASE_URL: ${VITE_API_BASE_URL}
#         VITE_SOCKET_URL: ${VITE_SOCKET_URL}
#         VITE_APP_NAME: ${VITE_APP_NAME}
#         VITE_DEFAULT_LANGUAGE: ${VITE_DEFAULT_LANGUAGE}
#         VITE_SUPPORTED_LANGUAGES: ${VITE_SUPPORTED_LANGUAGES}
#     env_file:
#       - .env
#     environment:
#       # 🔑 Ensure these env vars are available to Node
#       DATABASE_URL: postgres://postgres:postgres@db:5432/cebleu_db
#       SESSION_SECRET: ${SESSION_SECRET:-supersecret}
#       NODE_ENV: production
#       CLIENT_ORIGIN: ${CLIENT_ORIGIN:-http://localhost:5173}
#     ports:
#       - "127.0.0.1:5103:5000"
#     volumes:
#       - ./uploads:/app/uploads
#     restart: unless-stopped

#     # ✅ Wait for Postgres health before starting app
#     depends_on:
#       db:
#         condition: service_healthy

#     healthcheck:
#       test: ["CMD-SHELL", "wget -qO- http://localhost:5000/health || curl -fsS http://localhost:5000 || exit 1"]
#       interval: 30s
#       timeout: 5s
#       retries: 5

# volumes:
#   pg_data:


version: "3.8"

services:
  cebleu:
    container_name: cebleu
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_SOCKET_URL: ${VITE_SOCKET_URL}
        VITE_APP_NAME: ${VITE_APP_NAME}
        VITE_DEFAULT_LANGUAGE: ${VITE_DEFAULT_LANGUAGE}
        VITE_SUPPORTED_LANGUAGES: ${VITE_SUPPORTED_LANGUAGES}
    env_file:
      - .env
    ports:
      - "127.0.0.1:5103:5000"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5000/health || curl -fsS http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3