import { Carrier, ShippingOption } from './types';

export const mockCarriers: Carrier[] = [
  {
    id: '1',
    name: 'Yalidine',
    description: 'Leader de la livraison en Algérie avec plus de 1500 points relais',
    website: 'https://yalidine.com',
    support_phone: '023 10 23 63',
    contact_info: '023 10 23 63',
    max_weight: 30,
    is_active: true,
    base_price: 400,
    delivers_nationwide: true
  },
  {
    id: '2',
    name: 'ZR Express',
    description: 'Service de livraison rapide dans toute l\'Algérie',
    website: 'https://zrexpress.dz',
    support_phone: '021 55 66 77',
    contact_info: '021 55 66 77',
    max_weight: 25,
    is_active: true,
    base_price: 350,
    delivers_nationwide: true
  },
  {
    id: '3',
    name: 'Khadamat',
    description: 'Réseau de livraison couvrant 48 wilayas',
    website: 'https://khadamat.dz',
    support_phone: '025 88 99 00',
    contact_info: '025 88 99 00',
    max_weight: 20,
    is_active: true,
    base_price: 300,
    delivers_nationwide: true
  },
  {
    id: '4',
    name: 'Post Express',
    description: 'Service express d\'Algérie Poste',
    website: 'https://poste.dz',
    support_phone: '021 73 00 00',
    contact_info: '021 73 00 00',
    max_weight: 35,
    is_active: true,
    base_price: 250,
    delivers_nationwide: true
  },
  {
    id: '5',
    name: 'Quick Delivery',
    description: 'Livraison rapide dans les grandes villes',
    website: 'https://quickdelivery.dz',
    support_phone: '031 22 33 44',
    contact_info: '031 22 33 44',
    max_weight: 15,
    is_active: true,
    base_price: 320,
    delivers_nationwide: false,
    service_areas: ['Alger', 'Oran', 'Constantine', 'Annaba']
  },
  {
    id: '6',
    name: 'Safex Express',
    description: 'Service de livraison professionnel pour les entreprises',
    website: 'https://safexexpress.dz',
    support_phone: '021 91 92 93',
    contact_info: '021 91 92 93',
    max_weight: 50,
    is_active: true,
    base_price: 500,
    delivers_nationwide: true
  },
  {
    id: '7',
    name: 'Baridi Mob',
    description: 'Solution de paiement et livraison mobile',
    website: 'https://baridimob.dz',
    support_phone: '021 65 10 10',
    contact_info: '021 65 10 10',
    max_weight: 10,
    is_active: true,
    base_price: 280,
    delivers_nationwide: false,
    service_areas: ['Alger', 'Blida', 'Tipaza', 'Bouira']
  },
  {
    id: '8',
    name: 'AXA Delivery',
    description: 'Livraison assurée dans tout le territoire national',
    website: 'https://axadelivery.dz',
    support_phone: '026 18 19 20',
    contact_info: '026 18 19 20',
    max_weight: 40,
    is_active: true,
    base_price: 450,
    delivers_nationwide: true
  },
  {
    id: '9',
    name: 'Speed Courrier',
    description: 'Service de coursier rapide en milieu urbain',
    website: 'https://speedcourrier.dz',
    support_phone: '041 77 88 99',
    contact_info: '041 77 88 99',
    max_weight: 12,
    is_active: false,
    base_price: 200,
    delivers_nationwide: false,
    service_areas: ['Oran', 'Tlemcen', 'Sidi Bel Abbès']
  },
  {
    id: '10',
    name: 'National Courier',
    description: 'Réseau national de livraison avec suivi GPS',
    website: 'https://nationalcourier.dz',
    support_phone: '038 44 55 66',
    contact_info: '038 44 55 66',
    max_weight: 45,
    is_active: true,
    base_price: 380,
    delivers_nationwide: true
  },
  {
    id: '11',
    name: 'Nordest Express',
    description: 'Spécialiste de la livraison dans le Nord-Est algérien',
    website: 'https://nordestexpress.dz',
    support_phone: '031 42 43 44',
    contact_info: '031 42 43 44',
    max_weight: 25,
    is_active: true,
    base_price: 360,
    delivers_nationwide: false,
    service_areas: ['Constantine', 'Annaba', 'Skikda', 'Jijel', 'Guelma', 'El Tarf', 'Souk Ahras', 'Tébessa']
  },
  {
    id: '12',
    name: 'Colis Plus',
    description: 'Service de livraison économique pour particuliers et professionnels',
    website: 'https://colisplus.dz',
    support_phone: '023 77 78 79',
    contact_info: '023 77 78 79',
    max_weight: 20,
    is_active: true,
    base_price: 290,
    delivers_nationwide: true
  },
  {
    id: '13',
    name: 'Express DZ',
    description: 'Livraison express 24h/48h dans les principales villes',
    website: 'https://expressdz.com',
    support_phone: '021 88 89 90',
    contact_info: '021 88 89 90',
    max_weight: 30,
    is_active: true,
    base_price: 420,
    delivers_nationwide: false,
    service_areas: ['Alger', 'Oran', 'Constantine', 'Annaba', 'Sétif', 'Batna']
  },
  {
    id: '14',
    name: 'Livraison Rapide Algérie',
    description: 'Réseau de livraison couvrant tout le territoire avec points relais',
    website: 'https://lra.dz',
    support_phone: '025 33 34 35',
    contact_info: '025 33 34 35',
    max_weight: 35,
    is_active: true,
    base_price: 340,
    delivers_nationwide: true
  },
  {
    id: '15',
    name: 'Metro Express',
    description: 'Service de livraison urbaine dans les grandes métropoles',
    website: 'https://metroexpress.dz',
    support_phone: '041 56 57 58',
    contact_info: '041 56 57 58',
    max_weight: 15,
    is_active: true,
    base_price: 310,
    delivers_nationwide: false,
    service_areas: ['Alger', 'Oran', 'Constantine']
  },
  {
    id: '16',
    name: 'Djanet Logistics',
    description: 'Spécialiste de la livraison dans le Sud algérien',
    website: 'https://djanetlogistics.dz',
    support_phone: '029 82 83 84',
    contact_info: '029 82 83 84',
    max_weight: 40,
    is_active: true,
    base_price: 600,
    delivers_nationwide: false,
    service_areas: ['Ouargla', 'Tamanrasset', 'Adrar', 'Ghardaïa', 'El Oued', 'Biskra']
  },
  {
    id: '17',
    name: 'Flash Delivery',
    description: 'Livraison ultra-rapide en moins de 4 heures en milieu urbain',
    website: 'https://flashdelivery.dz',
    support_phone: '021 95 96 97',
    contact_info: '021 95 96 97',
    max_weight: 8,
    is_active: true,
    base_price: 500,
    delivers_nationwide: false,
    service_areas: ['Alger', 'Oran']
  },
  {
    id: '18',
    name: 'Atlas Transport',
    description: 'Transport et livraison dans les régions montagneuses',
    website: 'https://atlastransport.dz',
    support_phone: '027 61 62 63',
    contact_info: '027 61 62 63',
    max_weight: 50,
    is_active: true,
    base_price: 450,
    delivers_nationwide: false,
    service_areas: ['Tizi Ouzou', 'Béjaïa', 'Bouira', 'Médéa', 'Aïn Defla']
  },
  {
    id: '19',
    name: 'Horizon Express',
    description: 'Service de livraison avec garantie de délais',
    website: 'https://horizonexpress.dz',
    support_phone: '035 71 72 73',
    contact_info: '035 71 72 73',
    max_weight: 25,
    is_active: true,
    base_price: 380,
    delivers_nationwide: true
  },
  {
    id: '20',
    name: 'Green Delivery',
    description: 'Livraison écologique avec véhicules électriques',
    website: 'https://greendelivery.dz',
    support_phone: '021 47 48 49',
    contact_info: '021 47 48 49',
    max_weight: 12,
    is_active: true,
    base_price: 350,
    delivers_nationwide: false,
    service_areas: ['Alger', 'Blida', 'Boumerdès']
  },
  {
    id: '21',
    name: 'TMF Logistics',
    description: 'Transport routier & frigorifique spécialisé',
    website: 'https://tmf-logistics.com',
    support_phone: '034 19 62 72',
    contact_info: '+213 34 19 62 72, contact@tmf-logistics.com',
    max_weight: 60,
    is_active: true,
    base_price: 550,
    delivers_nationwide: true,
    service_areas: ['Akbou', 'Béjaïa', 'Sétif', 'Bordj Bou Arréridj']
  },
  {
    id: '22',
    name: 'Transmex',
    description: 'Transport exceptionnel & manutention industrielle',
    website: 'https://transmex.dz',
    support_phone: '021 83 90 56',
    contact_info: '+213 21 83 90 56, contact@transmex.dz',
    max_weight: 100,
    is_active: true,
    base_price: 800,
    delivers_nationwide: true,
    service_areas: ['Constantine', 'Alger', 'Oran']
  },
  {
    id: '23',
    name: 'HYPROC Shipping Co.',
    description: 'Transport maritime spécialisé hydrocarbures',
    website: 'https://www.hyproc.dz',
    support_phone: '041 79 38 55',
    contact_info: '+213 41 79 38 55, contact@hyproc.dz',
    max_weight: 200,
    is_active: true,
    base_price: 1200,
    delivers_nationwide: false,
    service_areas: ['Oran', 'Arzew', 'Mostaganem', 'Alger']
  },
  {
    id: '24',
    name: 'Air Algérie Cargo',
    description: 'Fret aérien national & international',
    website: 'https://airalgeriecargo.dz',
    support_phone: '041 591 029',
    contact_info: '+213 41 591 029, orn.cargo@airalgerie.dz',
    max_weight: 500,
    is_active: true,
    base_price: 2000,
    delivers_nationwide: true
  },
  {
    id: '25',
    name: 'Algérie Ferries',
    description: 'Transport maritime passagers & véhicules',
    website: 'https://algerieferries.dz',
    support_phone: '021 63 53 76',
    contact_info: '+213 21 63 53 76, drc.entmv@algerieferries.dz',
    max_weight: 1000,
    is_active: true,
    base_price: 1500,
    delivers_nationwide: false,
    service_areas: ['Alger', 'Oran', 'Annaba', 'Skikda', 'Béjaïa']
  },
  {
    id: '26',
    name: 'Yassir',
    description: 'VTC & Livraison urbaine à la demande',
    website: 'https://www.yassir.com',
    support_phone: '023 45 67 89',
    contact_info: 'support@yassir.io',
    max_weight: 5,
    is_active: true,
    base_price: 180,
    delivers_nationwide: false,
    service_areas: ['Alger', 'Oran', 'Constantine', 'Annaba', 'Sétif']
  },
  {
    id: '27',
    name: 'Anderson Logistique',
    description: 'Logistique e-commerce & solutions de stockage',
    website: 'https://www.andersonlogistique.com',
    support_phone: '023 70 70 35',
    contact_info: '+213 23 70 70 35, contact@andersonlogistique.com',
    max_weight: 75,
    is_active: true,
    base_price: 400,
    delivers_nationwide: false,
    service_areas: ['Alger', 'Blida', 'Bouira', 'Médéa']
  },
  {
    id: '28',
    name: 'Golden Triple Export',
    description: 'Export, transit & services douaniers',
    website: 'https://goldentripleexport.com',
    support_phone: '553 79 94 58',
    contact_info: '+213 553 79 94 58',
    max_weight: 150,
    is_active: true,
    base_price: 900,
    delivers_nationwide: true
  }
];

export const mockShippingOptions: ShippingOption[] = [
  {
    id: '1',
    carrier_id: '1',
    name: 'Livraison Standard',
    delivery_time: '2-3 jours',
    price_adjustment: 0,
    is_active: true
  },
  {
    id: '2',
    carrier_id: '1',
    name: 'Livraison Express',
    delivery_time: '24h',
    price_adjustment: 200,
    is_active: true
  },
  {
    id: '3',
    carrier_id: '2',
    name: 'Livraison Rapide',
    delivery_time: '1-2 jours',
    price_adjustment: 100,
    is_active: true
  },
  {
    id: '4',
    carrier_id: '11',
    name: 'Nord-Est Express',
    delivery_time: '24-48h',
    price_adjustment: 50,
    is_active: true
  },
  {
    id: '5',
    carrier_id: '17',
    name: 'Flash 4h',
    delivery_time: '4h',
    price_adjustment: 300,
    is_active: true
  },
  {
    id: '6',
    carrier_id: '21',
    name: 'TMF Frigorifique',
    delivery_time: '24-48h',
    price_adjustment: 150,
    is_active: true
  },
  {
    id: '7',
    carrier_id: '24',
    name: 'Air Cargo Express',
    delivery_time: '24h',
    price_adjustment: 500,
    is_active: true
  },
  {
    id: '8',
    carrier_id: '26',
    name: 'Yassir Express',
    delivery_time: '2-4h',
    price_adjustment: 80,
    is_active: true
  }
];
