// Export Arabic translations
export const ar = {
  common: {
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    create: 'إنشاء',
    search: 'بحث',
    filter: 'تصفية',
    sort: 'فرز',
    view: 'عرض',
    more: 'المزيد',
    less: 'أقل',
    all: 'الكل',
    none: 'لا شيء',
    back: 'عودة',
    next: 'التالي',
    previous: 'السابق',
    confirm: 'تأكيد',
    clear: 'مسح البحث',
    resetFilters: 'إعادة ضبط الفلاتر',
  },
  categories: {
    title: 'الفئات',
    subtitle: 'إدارة وتصنيف المنتجات والخدمات',
    treeView: 'عرض شجري',
    gridView: 'عرض شبكي',
    tableView: 'عرض جدولي',
    create: 'إنشاء فئة',
    update: 'تحديث الفئة',
    delete: 'حذف الفئة',
    editCategory: 'تعديل الفئة',
    addSubcategory: 'إضافة فئة فرعية',
    editSubcategory: 'تعديل فئة فرعية',
    deleteSubcategory: 'حذف فئة فرعية',
    name: 'اسم الفئة',
    description: 'وصف الفئة',
    parentCategory: 'الفئة الرئيسية',
    visibility: 'الرؤية',
    featured: 'مميزة',
    template: 'قالب',
    attributes: 'الخصائص',
    save: 'حفظ',
    cancel: 'إلغاء',
    search: 'بحث',
    filters: 'مرشحات',
    sortBy: 'ترتيب حسب',
    allCategories: 'جميع الفئات',
    popularCategories: 'الفئات الشائعة',
    recentCategories: 'الفئات الحديثة',
    categoryDetails: 'تفاصيل الفئة',
    categoryProducts: 'منتجات الفئة',
    addSubcategoryTo: 'إضافة فئة فرعية إلى',
    editCategoryDetails: 'تعديل تفاصيل الفئة',
    deleteCategoryConfirmation: 'هل أنت متأكد أنك تريد حذف هذه الفئة؟',
    deleteCategorySuccess: 'تم حذف الفئة بنجاح',
    visibilityUpdated: 'تم تحديث حالة الرؤية',
    featuredUpdated: 'تم تحديث حالة العرض المميز',
    templateApplied: 'تم تطبيق القالب',
    newCategory: 'فئة جديدة',
    editExistingCategory: 'تعديل فئة موجودة',
    noCategoriesFound: 'لا توجد فئات',
    addFirstCategory: 'أضف أول فئة لتبدأ',
    applyTemplateToCategory: 'تطبيق قالب على الفئة',
  },
  products: {
    title: 'المنتجات',
    subtitle: 'إدارة المنتجات والخدمات',
    create: 'إنشاء منتج',
    update: 'تحديث المنتج',
    delete: 'حذف المنتج',
    editProduct: 'تعديل المنتج',
    name: 'اسم المنتج',
    description: 'وصف المنتج',
    category: 'الفئة',
    price: 'السعر',
    quantity: 'الكمية',
    images: 'الصور',
    attributes: 'الخصائص',
    save: 'حفظ',
    cancel: 'إلغاء',
    search: 'بحث',
    filters: 'مرشحات',
    sortBy: 'ترتيب حسب',
    allProducts: 'جميع المنتجات',
    popularProducts: 'المنتجات الشائعة',
    recentProducts: 'المنتجات الحديثة',
    productDetails: 'تفاصيل المنتج',
    productReviews: 'تقييمات المنتج',
    addProductToCategory: 'إضافة منتج إلى الفئة',
    editProductDetails: 'تعديل تفاصيل المنتج',
    deleteProductConfirmation: 'هل أنت متأكد أنك تريد حذف هذا المنتج؟',
    deleteProductSuccess: 'تم حذف المنتج بنجاح',
    newProduct: 'منتج جديد',
    editExistingProduct: 'تعديل منتج موجود',
  },
  templates: {
    title: 'القوالب',
    subtitle: 'إدارة قوالب الحقول المخصصة',
    create: 'إنشاء قالب',
    management: 'إدارة القوالب',
    allTemplates: 'جميع القوالب',
    productTemplates: 'قوالب المنتجات',
    categoryTemplates: 'قوالب الفئات',
    noTemplates: 'لم يتم العثور على قوالب',
    createFirstTemplate: 'قم بإنشاء القالب الأول الخاص بك لتوحيد منتجاتك أو فئاتك',
    edit: 'تعديل القالب',
    new: 'قالب جديد',
    updated: 'تم تحديث القالب',
    updatedDesc: 'تم تحديث القالب {template} بنجاح.',
    added: 'تمت إضافة القالب',
    addedDesc: 'تمت إضافة القالب {template} بنجاح.',
    deleted: 'تم حذف القالب',
    deletedDesc: 'تم حذف القالب {template}.',
    error: 'خطأ',
    errorNameRequired: 'اسم القالب مطلوب.',
    searchPlaceholder: 'البحث في القوالب...',
    filters: 'تصفية',
    all: 'الكل',
    popular: 'شائع',
    recent: 'حديث',
    viewAllProductTemplates: 'عرض كل قوالب المنتجات',
    save: 'حفظ'
  },
};
