// Import or define the Translations type
import { Translations } from './utils';

// English translations
export const en = {
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    create: 'Create',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    view: 'View',
    more: 'More',
    less: 'Less',
    all: 'All',
    none: 'None',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    confirm: 'Confirm',
    clear: 'Clear search',
    resetFilters: 'Reset filters',
  },
  pages: {
    home: 'Home',
    categories: 'Categories',
    categoryManagement: 'Category Management',
    categoryTemplates: 'Category Templates',
    categoryBrowser: 'Browse Categories',
    products: 'Products',
    productManagement: 'Product Management',
    templates: 'Templates',
    templateManagement: 'Template Management'
  },
  categories: {
    title: 'Categories',
    subtitle: 'Manage your product categories',
    create: 'Create Category',
    edit: 'Edit Category',
    delete: 'Delete Category',
    nameRequired: 'Category name is required',
    categoryAdded: 'Category Created',
    categoryAddedDesc: 'Category {category} has been created successfully',
    categoryUpdated: 'Category Updated',
    categoryUpdatedDesc: 'Category {category} has been updated successfully',
    categoryDeleted: 'Category Deleted',
    categoryDeletedDesc: 'Category {category} has been deleted successfully',
    confirmDelete: 'Are you sure you want to delete this category?',
    confirmDeleteDesc: 'This action cannot be undone.',
    subcategoryCreated: 'Subcategory Created',
    subcategoryCreatedDesc: 'A subcategory has been created for {category}',
    treeView: 'Tree View',
    grid: 'Grid View',
    table: 'Table View',
    search: 'Search categories...',
    filter: {
      all: 'All',
      visible: 'Visible',
      hidden: 'Hidden',
      featured: 'Featured',
    },
    sort: {
      nameAsc: 'Name (A-Z)',
      nameDesc: 'Name (Z-A)',
      newest: 'Newest',
      oldest: 'Oldest',
    },
    visibility: 'Visibility',
    visible: 'Visible',
    hidden: 'Hidden',
    featured: 'Featured',
    items: '{count} items',
    empty: 'No categories found',
    emptyDesc: 'Start by creating your first category',
    addSubcategory: 'Add Subcategory',
    categoryTemplates: 'Category Templates',
    templatesInfo: 'Get started quickly with pre-built category structures for various industries.',
    viewAllTemplates: 'View All Templates'
  },
  products: {
    editor: 'Product Editor',
    generalInfo: 'General Information',
    name: 'Product Name',
    namePlaceholder: 'Enter product name',
    nameRequired: 'Product name is required',
    shortDescription: 'Short Description',
    shortDescPlaceholder: 'Brief description of the product',
    fullDescription: 'Full Description',
    description: 'Description',
    details: 'Details',
    variations: 'Variations',
    mainFeatures: 'Main Features',
    addFeature: 'Add Feature',
    addFeaturesHint: 'Add features to highlight the main selling points of the product.',
    featurePlaceholder: 'E.g. High-resolution screen',
    packageContents: 'Package Contents',
    packageContentsPlaceholder: 'E.g. 1x Headphones, 1x Charging cable, 1x User manual',
    warranty: 'Warranty & Return Information',
    warrantyPlaceholder: 'Warranty and return policy information',
    priceInfo: 'Price Information',
    price: 'Price',
    comparePrice: 'Compare at Price',
    inventory: 'Inventory',
    sku: 'SKU (Stock Keeping Unit)',
    barcode: 'Barcode (EAN, UPC)',
    quantity: 'Quantity in Stock',
    dimensions: 'Dimensions & Weight',
    length: 'Length',
    width: 'Width',
    height: 'Height',
    weight: 'Weight',
    productVariations: 'Product Variations',
    addVariation: 'Add Variation',
    variationsDescription: 'Variations allow you to offer different versions of the same product (sizes, colors, etc.)',
    statusVisibility: 'Status & Visibility',
    active: 'Product Active',
    activeDescription: 'The product will be visible on the store',
    featured: 'Featured Product',
    featuredDescription: 'Feature this product on the homepage',
    category: 'Category',
    selectCategory: 'Select Category',
    categoryDescription: 'Choose the main category for the product',
    images: 'Images',
    dragImagesHere: 'Drag and drop images here or click to upload',
    addImages: 'Add Images',
    uploadImages: 'Image Upload',
    uploadImagesDescription: 'Image upload will be available soon',
    saved: 'Product Saved',
    savedDescription: 'Product {name} has been saved successfully.',
    seoTitle: 'SEO Title',
    seoTitlePlaceholder: 'Title for search engines',
    seoTitleDescription: 'If empty, the product name will be used',
    seoDescription: 'SEO Description',
    seoDescriptionPlaceholder: 'Description for search engines',
    seoDescriptionHelp: 'Recommended: 150-160 characters',
    keywords: 'Keywords',
    keywordsPlaceholder: 'keyword1, keyword2, keyword3'
  },
  templates: {
    title: 'Templates',
    subtitle: 'Manage custom field templates',
    create: 'Create template',
    update: 'Update',
    management: 'Template Management',
    allTemplates: 'All templates',
    productTemplates: 'Product templates',
    categoryTemplates: 'Category templates',
    noTemplates: 'No templates found',
    createFirstTemplate: 'Create your first template to standardize your products or categories',
    edit: 'Edit template',
    new: 'New template',
    updated: 'Template updated',
    updatedDesc: 'The template {template} has been successfully updated.',
    added: 'Template added',
    addedDesc: 'The template {template} has been successfully added.',
    deleted: 'Template deleted',
    deletedDesc: 'The template {template} has been deleted.',
    error: 'Error',
    errorNameRequired: 'Template name is required.',
    searchPlaceholder: 'Search templates...',
    filters: 'Filters',
    all: 'All',
    popular: 'Popular',
    recent: 'Recent',
    viewAllProductTemplates: 'View all product templates',
    save: 'Save template',
    fields: 'Fields'
  }
};
