// Import the Translations type
import { Translations } from './utils';

// French translations
export const fr = {
  common: {
    save: 'Sauvegarder',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    create: 'Créer',
    search: 'Rechercher',
    filter: 'Filtrer',
    sort: 'Trier',
    view: 'Voir',
    more: 'Plus',
    less: 'Moins',
    all: 'Tous',
    none: 'Aucun',
    back: 'Retour',
    next: 'Suivant',
    previous: 'Précédent',
    confirm: 'Confirmer',
    clear: 'Effacer la recherche',
    resetFilters: 'Réinitialiser les filtres',
  },
  pages: {
    home: 'Accueil',
    categories: 'Catégories',
    categoryManagement: 'Gestion des catégories',
    categoryTemplates: 'Modèles de catégories',
    categoryBrowser: 'Parcourir les catégories',
    products: 'Produits',
    productManagement: 'Gestion des produits',
    templates: 'Modèles',
    templateManagement: 'Gestion des modèles'
  },
  categories: {
    title: 'Catégories',
    subtitle: 'Gérez vos catégories de produits',
    create: 'Créer une catégorie',
    edit: 'Modifier la catégorie',
    delete: 'Supprimer la catégorie',
    nameRequired: 'Le nom de la catégorie est requis',
    categoryAdded: 'Catégorie créée',
    categoryAddedDesc: 'La catégorie {category} a été créée avec succès',
    categoryUpdated: 'Catégorie mise à jour',
    categoryUpdatedDesc: 'La catégorie {category} a été mise à jour avec succès',
    categoryDeleted: 'Catégorie supprimée',
    categoryDeletedDesc: 'La catégorie {category} a été supprimée avec succès',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer cette catégorie?',
    confirmDeleteDesc: 'Cette action ne peut pas être annulée.',
    subcategoryCreated: 'Sous-catégorie créée',
    subcategoryCreatedDesc: 'Une sous-catégorie a été créée pour {category}',
    treeView: 'Vue en arbre',
    tree: 'Arborescence',
    grid: 'Vue en grille',
    table: 'Vue en tableau',
    search: 'Rechercher des catégories...',
    add: 'Ajouter une catégorie',
    children: 'Sous-catégories',
    noRecords: 'Aucune catégorie trouvée',
    createFirst: 'Commencez par créer votre première catégorie',
    addSuccess: 'Catégorie ajoutée',
    updateSuccess: 'Catégorie mise à jour',
    deleteSuccess: 'Catégorie supprimée',
    filter: {
      all: 'Toutes',
      visible: 'Visibles',
      hidden: 'Masquées',
      featured: 'En vedette',
    },
    sort: {
      nameAsc: 'Nom (A-Z)',
      nameDesc: 'Nom (Z-A)',
      newest: 'Plus récentes',
      oldest: 'Plus anciennes',
    },
    visibility: 'Visibilité',
    visible: 'Visible',
    hidden: 'Masquée',
    featured: 'En vedette',
    items: '{count} éléments',
    empty: 'Aucune catégorie trouvée',
    emptyDesc: 'Commencez par créer votre première catégorie',
    addSubcategory: 'Ajouter une sous-catégorie',
    categoryTemplates: 'Modèles de catégories',
    templatesInfo: 'Démarrez rapidement avec des structures de catégories prédéfinies pour différents secteurs.',
    viewAllTemplates: 'Voir tous les modèles',
    selectTemplate: 'Sélectionner un modèle',
    selectTemplateDescription: 'Choisissez un modèle pour votre nouvelle catégorie',
    noTemplate: 'Aucun modèle',
    continue: 'Continuer',
    name: 'Nom',
    namePlaceholder: 'Entrez le nom de la catégorie',
    description: 'Description',
    descriptionPlaceholder: 'Entrez une description de la catégorie',
    usingTemplate: 'Utilisation du modèle',
    subCategoryOf: 'Sous-catégorie de',
    saving: 'Sauvegarde en cours',
  },
  templates: {
    title: 'Modèles',
    create: 'Créer un modèle',
    update: 'Mettre à jour',
    management: 'Gestion des modèles',
    allTemplates: 'Tous les modèles',
    productTemplates: 'Modèles de produits',
    categoryTemplates: 'Modèles de catégories',
    noTemplates: 'Aucun modèle trouvé',
    createFirstTemplate: 'Créez votre premier modèle pour standardiser vos produits ou catégories',
    edit: 'Modifier le modèle',
    new: 'Nouveau modèle',
    updated: 'Modèle mis à jour',
    updatedDesc: 'Le modèle {template} a été mis à jour avec succès.',
    added: 'Modèle ajouté',
    addedDesc: 'Le modèle {template} a été ajouté avec succès.',
    deleted: 'Modèle supprimé',
    deletedDesc: 'Le modèle {template} a été supprimé.',
    error: 'Erreur',
    errorNameRequired: 'Le nom du modèle est requis.',
    searchPlaceholder: 'Rechercher des modèles...',
    filters: 'Filtres',
    all: 'Tous',
    popular: 'Populaires',
    recent: 'Récents',
    viewAllProductTemplates: 'Voir tous les modèles de produits',
    notFound: 'Modèle non trouvé',
    notFoundDesc: 'Le modèle demandé n\'a pas été trouvé.',
    save: 'Sauvegarder le modèle',
    fields: 'Champs'
  },
  products: {
    title: 'Produits',
    subtitle: 'Gérez vos produits',
    editor: 'Éditeur de produit',
    generalInfo: 'Informations générales',
    name: 'Nom du produit',
    namePlaceholder: 'Entrez le nom du produit',
    nameRequired: 'Le nom du produit est requis',
    shortDescription: 'Description courte',
    shortDescPlaceholder: 'Brève description du produit',
    fullDescription: 'Description complète',
    description: 'Description',
    details: 'Détails',
    variations: 'Variations',
    mainFeatures: 'Caractéristiques principales',
    addFeature: 'Ajouter une caractéristique',
    addFeaturesHint: 'Ajoutez des caractéristiques pour mettre en avant les points forts du produit.',
    featurePlaceholder: 'Ex: Écran haute résolution',
    packageContents: 'Contenu du package',
    packageContentsPlaceholder: 'Ex: 1x Écouteurs, 1x Câble de chargement, 1x Manuel d\'utilisation',
    warranty: 'Garantie & Informations de retour',
    warrantyPlaceholder: 'Informations sur la garantie et la politique de retour',
    priceInfo: 'Informations de prix',
    price: 'Prix',
    comparePrice: 'Prix de comparaison',
    inventory: 'Inventaire',
    sku: 'SKU (Unité de gestion de stock)',
    barcode: 'Code-barres (EAN, UPC)',
    quantity: 'Quantité en stock'
  },
  fieldGroups: {
    title: 'Groupes de champs',
    type: 'Type de groupe',
    grid: 'Grille',
    table: 'Tableau',
    rows: 'Lignes',
    name: 'Nom du groupe',
    namePlaceholder: 'Entrez un nom pour le groupe',
    fields: 'Champs',
    addField: 'Ajouter un champ',
    noFields: 'Aucun champ dans ce groupe',
    addGroup: 'Ajouter un groupe',
    removeGroup: 'Supprimer le groupe',
    confirmRemove: 'Êtes-vous sûr de vouloir supprimer ce groupe?',
    createGroup: 'Créer le groupe',
    columns: 'Colonnes',
    spacingValues: {
      small: 'Petit',
      medium: 'Moyen',
      large: 'Grand'
    },
    spacing: 'Espacement',
    layoutPreview: 'Aperçu de la mise en page',
    layoutPreviewDesc: 'Cette fonctionnalité sera disponible prochainement',
    groups: 'Groupes',
    fieldsManagement: 'Gestion des champs'
  }
};

// Default export for backwards compatibility
export default fr;
